# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [ ]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
royxat = [1,2,3]
massiv = np.array(royxat)
massiv

array([1, 2, 3])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
nol = np.zeros(9)
nol.size

9

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
vek = np.zeros(12)
vek[5] = 1
vek

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
vek1 = np.arange(20,59)
vek1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
vek2 = np.arange(10)
vek2[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
mat = np.arange(12,21)
mat.reshape(3,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
mm = [3,7,0,0,9,0]
m = np.nonzero(mm)
m

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
siz = np.random.rand(2,2,2)
print(siz)

[[[0.74330657 0.79846089]
  [0.85309842 0.71059387]]

 [[0.79607136 0.39223449]
  [0.09011096 0.74029342]]]


#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:
tas = np.random.randn(81)
tas2 = tas.reshape(9,9)
tas2
max= max(tas)
max
min = min(tas)
min

-2.556756550736259

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
bir = np.ones(18)
bir1= bir.reshape(6,3)
bir1
ikki = np.ones(12)
ikki2 = ikki.reshape(3,4)

nat= np.dot(bir1,ikki2)
nat

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
nima = np.sum(range(5),-1)
nima
nima1 = np.sum(range(5),-1)
nima1

nat = np.dot(nima, nima1)
nat

100

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
x=[1, 2]
y= [3, 4]
x > y
x >= y
x < y
x <= y

True

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) // np.array(0)  #0
np.array(0) / np.array(0)  #nan
np.array([np.nan]).astype(int).astype(float) #-9.22

<ipython-input-15-00e4952b9542>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)  #0
<ipython-input-15-00e4952b9542>:2: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)  #nan
<ipython-input-15-00e4952b9542>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float) #-9.22


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [ ]:
ixt0 = np.arange(5)
ixt1 = (3,8)
ixt2 =  np.intersect1d(ixt0,ixt1)
ixt2


array([3])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
yar = np.random.randn(10)
yar
yar1 = np.floor(yar)
yar1
yar2 = np.trunc(yar)
yar2
yar3 = yar.astype
yar3
print(yar3)


<built-in method astype of numpy.ndarray object at 0x7b5641a54ab0>


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [ ]:
olch = np.arange(9)
olch1 = olch.reshape(3,3)
olch1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [ ]:
tt = np.random.rand(10)
tt2 = np.sort(tt)
print(tt2)

[0.05999951 0.08636014 0.1999847  0.23053559 0.24142249 0.43419573
 0.7140705  0.73364395 0.77097907 0.98029187]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [ ]:
A = np.random.randn(5)
A
B= np.random.randn(5)
B
bri = np.allclose(A,B)
bri
iki = np.array_equal(A,B)
iki

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [ ]:
bir = np.ones(18)
bir1= bir.reshape(6,3)
bir1
ikki = np.ones(12)
ikki2 = ikki.reshape(3,4)

nat= np.dot(bir1,ikki2)
nat

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [ ]:
iborat = np.random.randn(5)
iborat
ibor = np.argmax(iborat)
ibor

1

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
kecha = np.datetime64('2025-01-03')
print(kecha)
bugun = np.datetime64('2020-01-04')
print(bugun)
ertaga = np.datetime64('2025-01-05')
print(ertaga)

2025-01-03
2020-01-04
2025-01-05


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:

bowi = np.datetime64('2016-01-01')
oxiri = np.datetime64('2016-02-01')
barcha = np.arange(bowi, oxiri,dtype= 'datetime64[D]')
print(barcha)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [ ]:
yar = np.random.randn(10)
yar
yar1 = np.floor(yar)
yar1
yar2 = np.trunc(yar)
yar2
yar3 = yar.astype
yar3

<function ndarray.astype>

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [ ]:
massi1 = np.arange(5)
massi1
massi2 = np.arange(6,10)
massi2


array([6, 7, 8, 9])

In [ ]:
tez = np.add.reduce(massi1)
tez

10

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [ ]:
vektr =np.array([1,2,3,4,5])
nolli = 3
nollilar = np.zeros(len(vektr) * nolli + len(vektr) - nolli, dtype =int)
nollilar [:: nolli + 1] = vektr
print(nollilar)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [ ]:
from numpy.lib.stride_tricks import as_strided
a = np.arange(1,15)
shape=(5,3)
stride = (a.strides[0], a.strides[0])
b = as_strided(a,shape=shape, strides= stride)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [ ]:
ixti = [1,2,3,3,4,4,5,6,6,7]
ixti1 = np.bincount(ixti)
oxwaw = np.where (ixti1 > 1)[0]
print(ixti1)
print(oxwaw)

[0 1 1 2 2 1 2 1]
[3 4 6]


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`